/*
** namedef.h
**
** common names
**
**---------------------------------------------------------------------------
**
** Copyright 1999-2016 Marisa Heit
** Copyright 2010-2016 Christoph Oelckers
** Copyright 2017-2025 GZDoom Maintainers and Contributors
** Copyright 2025-2026 UZDoom Maintainers and Contributors
**
** SPDX-License-Identifier: GPL-3.0-or-later
**
**---------------------------------------------------------------------------
**
** Code written prior to 2026 is also licensed under:
**
** SPDX-License-Identifier: BSD-3-Clause
**
**---------------------------------------------------------------------------
**
*/

// clang-format off

// This is here to make my editor not have a meltdown every time I open this
// file. Since everywhere this file is included already defines `xx`, this
// does nothing, but it will give the compiler enough context to be happy.
#ifndef xx
#define xx(n)
#define xy(n,s)
#define xa(a,n)
#endif

// 'None' must always be the first name.
xx(None)
xx(Null)
xx(_)

xx(Super)
xx(Object)
xx(Actor)
xx(Class)
xx(Thinker)
xx(VisualThinker)
xx(Crosshairs)

xx(Untranslated)

// Render styles
xx(Normal)
xx(SoulTrans)
xx(OptFuzzy)
xx(Add)
xx(Shaded)
xx(AddShaded)
xx(TranslucentStencil)
xx(Shadow)
xx(Subtract)
xx(Subtractive)
xx(FillColor)
xx(ColorBlend)
xx(ColorAdd)
xx(Multiply)

// Special names for compiler backend
xx(Name)
xx(Clamp)
xx(Abs)
xx(Random)
xx(FRandom)
xx(Random2)
xx(RandomPick)
xx(FRandomPick)
xx(SetRandomSeed)
xx(CRandom)
xx(CFRandom)
xx(CRandom2)
xx(CRandomPick)
xx(CFRandomPick)
xx(CSetRandomSeed)
xx(BuiltinRandomSeed)
xx(BuiltinNew)
xx(GetClass)
xx(GetParentClass)
xx(GetClassName)
xx(IsAbstract)
xx(GetDefaultByType)
xx(Floor)
xx(Exp)
xx(Log)
xx(Log10)
xx(Ceil)
xx(ACos)
xx(ASin)
xx(ATan)
xx(Cos)
xx(Sin)
xx(Tan)
xx(CosH)
xx(SinH)
xx(TanH)
xx(Round)
xx(ATan2)
xx(VectorAngle)
xx(Sqrt)
xx(New)

xx(Static)
xx(Staticconst)

// compatibility crap that GZDoom needs in the backend.
xx(ACS_NamedExecuteWithResult)
xx(__decorate_internal_int__)
xx(__decorate_internal_bool__)
xx(__decorate_internal_float__)

// Per-actor sound channels (for deprecated PlaySoundEx function) Do not separate this block!!!
xx(Auto)
xx(Weapon)
xx(Voice)
xx(Item)
xx(Body)
xx(SoundSlot5)
xx(SoundSlot6)
xx(SoundSlot7)

xx(LevelLocals)
xx(Level)

xy(menu_cursor, "menu/cursor")
xy(menu_choose, "menu/choose")
xy(menu_backup, "menu/backup")
xy(menu_clear, "menu/clear")
xy(menu_dismiss, "menu/dismiss")
xy(menu_change, "menu/change")
xy(menu_advance, "menu/advance")

// basic type names
xx(Default)
xx(sByte)
xx(Byte)
xx(Short)
xx(uShort)
xx(Int)
xx(uInt)
xx(Bool)
xx(uint8)
xx(int8)
xx(uint16)
xx(int16)
xx(Float)
xx(Float32)
xx(Float64)
xx(Double)
xx(String)
xx(Vector)
xx(Map)
xx(MapIterator)
xx(Array)
xx(Function)
xx(Include)
xx(Sound)
xx(State)
xx(Fixed)
xx(Vector2)
xx(Vector3)
xx(Vector4)
xx(Quat)
xx(FVector2)
xx(FVector3)
xx(FVector4)
xx(FQuat)
xx(let)
xx(BlockThingsIterator)
xx(BlockLinesIterator)
xx(ActorIterator)
xx(ThinkerIterator)

xx(Min)
xx(Max)
xx(Min_Normal)
xx(Min_Denormal)
xx(Epsilon)
xx(Equal_Epsilon)
xx(NaN)
xx(Infinity)
xx(Dig)
xx(Min_Exp)
xx(Max_Exp)
xx(Mant_Dig)
xx(Min_10_Exp)
xx(Max_10_Exp)

// implicit function parameters
xx(self)
xx(invoker)
xx(stateinfo)

xx(DamageFunction)
xx(Length)
xx(LengthSquared)
xx(Sum)
xx(Unit)
xx(Angle)
xx(PlusZ)
xx(Conjugate)
xx(Inverse)
xx(ToVector)
xx(Size)
xx(Push)
xx(Insert)
xx(InsertNew)
xx(Remove)
xx(Get)
xx(GetIfExists)
xx(GetValue)
xx(GetKey)
xx(SetValue)
xx(CheckKey)
xx(CheckValue)
xx(Value)
xx(Copy)
xx(Move)
xx(Voidptr)
xx(StateLabel)
xx(SpriteID)
xx(TextureID)
xx(TranslationID)
xx(Overlay)
xx(IsValid)
xx(IsNull)
xx(IsEmpty)
xx(IsFixed)
xx(IsKeep)
xx(Exists)
xx(SetInvalid)
xx(SetNull)
xx(SetEmpty)
xx(SetFixed)
xx(SetKeep)
xx(Key)
xx(Index)
xx(Find)
xx(Call)

xx(Yes)
xx(No)

// color channels
xx(a)
xx(r)
xx(g)
xx(b)

xx(X)
xx(Y)
xx(Z)
xx(W)
xx(XY)
xx(XYZ)

xx(Prototype)
xx(Void)
xx(Label)
xx(Pointer)
xx(Enum)
xx(StaticArray)
xx(DynArray)
xx(Struct)
xx(ReflectType)
xx(MessageBoxMenu)

xx(Both)
xx(Physical)
xx(Visual)

// blacklisted former CVARs (used by common menu code)
xx(snd_waterlp)
xx(snd_output)
xx(snd_output_format)
xx(snd_speakermode)
xx(snd_resampler)
xx(AlwaysRun)

// menu names
xx(MainMenu)
xx(EpisodeMenu)
xx(SkillMenu)
xx(Startgame)
xx(StartgameConfirm)
xx(StartgameConfirmed)
xx(LoadgameMenu)
xx(SavegameMenu)
xx(OptionsMenu)
xx(OptionsMenuSimple)
xx(OptionsMenuFull)
xx(QuitMenu)
xx(SaveMenu)
xx(EndGameMenu)
xx(HelpMenu)
xx(SoundMenu)
xx(ConfirmPlayerReset)
xx(JoystickOptions)

xx(OptionMenuItemSubmenu)
xx(OptionMenuItemCommand)
xx(OptionMenuItemControlBase)
xx(OptionMenuItemOptionBase)
xx(OptionMenuSliderBase)
xx(OptionMenuFieldBase)
xx(OptionMenuItemColorPicker)
xx(OptionMenuItemStaticText)
xx(OptionMenuItemStaticTextSwitchable)

xx(InternalHandler)

xx(Color)

xx(Mididevices)
xx(Aldevices)
xx(Alresamplers)

// Decorate compatibility functions
xx(BuiltinRandom)
xx(BuiltinRandom2)
xx(BuiltinFRandom)
xx(BuiltinNameToClass)
xx(BuiltinClassCast)
xx(BuiltinFunctionPtrCast)
xx(BuiltinFindTranslation)
xx(HandleDeprecatedFlags)
xx(CheckDeprecatedFlags)

xx(ScreenJobRunner)
xx(Action)

// These are used for the stringtable, and are probably of no use elsewhere
// lowercase are old representations, UPPERCASE are ietf lang tags
xy(LANG_BE, "be")
xy(LANG_EN_AU, "en-AU")
xy(LANG_EN_BZ, "en-BZ")
xy(LANG_EN_CA, "en-CA")
xy(LANG_EN_GB, "en-GB")
xy(LANG_EN_GB_WALES, "en-GB-wales")
xy(LANG_EN_IE, "en-IE")
xy(LANG_EN_IN, "en-IN")
xy(LANG_EN_JM, "en-JM")
xy(LANG_EN_NZ, "en-NZ")
xy(LANG_EN_TT, "en-TT")
xy(LANG_EN_US, "en-US")
xy(LANG_EN_ZA, "en-ZA")
xy(LANG_ES, "es")
xy(LANG_ES_AR, "es-AR")
xy(LANG_ES_BO, "es-BO")
xy(LANG_ES_BZ, "es-BZ")
xy(LANG_ES_CL, "es-CL")
xy(LANG_ES_CO, "es-CO")
xy(LANG_ES_CR, "es-CR")
xy(LANG_ES_DO, "es-DO")
xy(LANG_ES_EC, "es-EC")
xy(LANG_ES_GT, "es-GT")
xy(LANG_ES_HN, "es-HN")
xy(LANG_ES_MX, "es-MX")
xy(LANG_ES_PH, "es-PH")
xy(LANG_ES_PY, "es-PY")
xy(LANG_ES_SV, "es-SV")
xy(LANG_ES_US, "es-US")
xy(LANG_ES_VE, "es-VE")
xy(LANG_JA, "ja")
xy(LANG_NB_NO, "nb-NO")
xy(LANG_PT, "pt")
xy(LANG_PT_BR, "pt-BR")
xy(LANG_ZH_HANS, "zh-Hans")
xy(LANG_ZH_HANT, "zh-Hant")
xy(LANG_by, "by")
xy(LANG_chs, "chs")
xy(LANG_cht, "cht")
xy(LANG_ena, "ena")
xy(LANG_enb, "enb")
xy(LANG_enc, "enc")
xy(LANG_eng, "eng")
xy(LANG_eni, "eni")
xy(LANG_enj, "enj")
xy(LANG_enl, "enl")
xy(LANG_ens, "ens")
xy(LANG_ent, "ent")
xy(LANG_enw, "enw")
xy(LANG_enz, "enz")
xy(LANG_esa, "esa")
xy(LANG_esb, "esb")
xy(LANG_esc, "esc")
xy(LANG_esd, "esd")
xy(LANG_ese, "ese")
xy(LANG_esf, "esf")
xy(LANG_esg, "esg")
xy(LANG_esh, "esh")
xy(LANG_esi, "esi")
xy(LANG_esl, "esl")
xy(LANG_esm, "esm")
xy(LANG_esn, "esn")
xy(LANG_eso, "eso")
xy(LANG_esr, "esr")
xy(LANG_ess, "ess")
xy(LANG_esu, "esu")
xy(LANG_esv, "esv")
xy(LANG_esy, "esy")
xy(LANG_esz, "esz")
xy(LANG_jp, "jp")
xy(LANG_nb, "nb")
xy(LANG_ptg, "ptg")

// clang-format on
