name: Continuous Integration

on: [push, pull_request]

jobs:
  this-is-a-test:
    if: always()
    runs-on: ubuntu-latest
    name: Testing some stuff
    steps:
      - name: A
        run: |
          false

