name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }} | ${{ matrix.config.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Visual Studio 2022
          os: windows-2022
          build_type: Release

        - name: Visual Studio 2022
          os: windows-2022
          build_type: Debug

        - name: macOS
          os: macos-14
          deps_cmdline: brew install libvpx
          build_type: Release

        - name: macOS
          os: macos-14
          extra_options: -G Xcode -DDYN_OPENAL=OFF
          deps_cmdline: brew install libvpx
          build_type: Debug

        # - name: Linux GCC 9
        #   os: ubuntu-22.04
        #   extra_options: -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9
        #   deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
        #   build_type: RelWithDebInfo
        #
        # - name: Linux GCC 12 # last known good
        #   os: ubuntu-22.04
        #   extra_options: -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12
        #   deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
        #   build_type: MinSizeRel
        #
        # - name: Linux Clang 11
        #   os: ubuntu-22.04
        #   extra_options: -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
        #   deps_cmdline: sudo apt-get update && sudo apt-get install clang-11 libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
        #   build_type: Debug
        #
        # - name: Linux Clang 15 # last known good
        #   os: ubuntu-22.04
        #   extra_options: -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15
        #   deps_cmdline: sudo apt-get update && sudo apt-get install clang-15 libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
        #   build_type: Release

        - name: Linux GCC
          os: ubuntu-latest
          deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
          build_type: Debug

        - name: Linux Clang
          os: ubuntu-latest
          extra_options: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
          build_type: Release

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ -n "${{ matrix.config.deps_cmdline }}" ]]; then
          eval ${{ matrix.config.deps_cmdline }}
        fi
        mkdir build
        if [[ "${{ runner.os }}" == 'macOS' ]]; then
          export ZMUSIC_PACKAGE=zmusic-1.1.14-macos-arm.tar.xz
        elif [[ "${{ runner.os }}" == 'Linux' ]]; then
          export ZMUSIC_PACKAGE=zmusic-1.1.14-linux.tar.xz
        fi
        if [[ -n "${ZMUSIC_PACKAGE}" ]]; then
          cd build
          wget -q "https://github.com/coelckers/gzdoom/releases/download/ci_deps/${ZMUSIC_PACKAGE}"
          tar -xf "${ZMUSIC_PACKAGE}"
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_PREFIX_PATH=`pwd`/build/zmusic -DPK3_QUIET_ZIPDIR=ON ${{ matrix.config.extra_options }} .

    - name: Build
      shell: bash
      run: |
        export MAKEFLAGS=--keep-going
        cmake --build build --config ${{ matrix.config.build_type }} --parallel 3

    - name: Create Package
      shell: bash
      run: |
        function fetch() { { curl -L "$3" | tee "$1" | sha1sum ; } && { echo "$2 $1" | sha1sum -c - ; } ; }

        cd build
        mkdir package

        7z a package/licenses.zip ../docs/licenses/*

        if [[ "${{ runner.os }}" == 'Windows' ]]; then

            fetch gzdoom.zip \
                2b3e7eac9e13bf88d27865165a1596de5778eb1a \
                https://github.com/ZDoom/gzdoom/releases/download/g4.14.2/gzdoom-4-14-2-windows.zip \
            unzip -j gzdoom.zip zmusic.dll -d package

            fetch oalsoft.zip \
                7a9871038cb8eb954b4f723c9f86b248f914fc59 \
                https://github.com/kcat/openal-soft/releases/download/1.23.1/openal-soft-1.23.1-bin.zip
            unzip -j oalsoft.zip openal-soft-1.23.1-bin/bin/Win64/soft_oal.dll -d package

            fetch sndfile.zip \
                610569766aa1c138044a30af43db6ec6195ed164 \
                https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2-win64.zip
            unzip -j sndfile.zip libsndfile-1.2.2-win64/bin/sndfile.dll -d package

            mkdir package/soundfonts
            cp ../soundfont/uzdoom.sf2 package/soundfonts

            mkdir package/fm_banks
            cp ../fm_banks/GENMIDI.GS.wopl ../fm_banks/gs-by-papiezak-and-sneakernets.wopn package/fm_banks

            cp ${{ matrix.config.build_type }}/uzdoom.exe ${{ matrix.config.build_type }}/*.pk3 package

        elif [[ "${{ runner.os }}" == 'macOS' ]]; then

            if [[ "${{ matrix.config.build_type }}" != 'Release' ]]; then
                mv ${{ matrix.config.build_type }}/uzdoom.app uzdoom.app
            fi
            mv package/licenses.zip uzdoom.app
            # copy fm_banks + soundfonts ?
            cp -r uzdoom.app package

        elif [[ "${{ runner.os }}" == 'Linux' ]]; then

            ldd ./uzdoom

            mkdir AppDir
            cmake --install . --prefix "$(realpath AppDir)/usr"

            fetch gzdoom.deb \
                554bb637cfc6aa969dc4c0cd2f1d4e0b780cd58f \
                https://github.com/ZDoom/gzdoom/releases/download/g4.14.2/gzdoom_4.14.2_amd64.deb
            dpkg --fsys-tarfile gzdoom.deb | tar -xO ./opt/gzdoom/libzmusic.so.1 > libzmusic.so.1
            mkdir -p "$(realpath AppDir)/usr/lib/x86_64-linux-gnu"
            mv libzmusic.so.1 "$(realpath AppDir)/usr/lib/x86_64-linux-gnu/"

            sudo apt-get install libfuse2 # renamed to libfuse2t64 in later releases

            fetch appimage-builder \
                6f83a789f6c47a745b97d1b0b3f1df2e7eea7a09 \
                https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
            chmod +x appimage-builder

            export GIT_DESCRIBE="${{ steps.ghd.outputs.describe }}"
            ./appimage-builder --skip-tests --recipe ../tools/AppImageBuilder.yml
            cp *.AppImage package

            rm package/licenses.zip

        fi

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        path: build/package
        name: ${{ matrix.config.name }} ${{ matrix.config.build_type }}

    - name: List Build Directory
      if: always()
      shell: bash
      run: |
        git status
        ls -lR build
