name: Nightly Builds

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [trunk, experimental]
    types: [completed]

jobs:
  preview:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'trunk' }}
    uses: ./.github/workflows/release_core.yml
    permissions:
      contents: write
      actions: read
    with:
      title: Preview
      run-id: ${{ github.event.workflow_run.id }}
      run-url: ${{ github.event.workflow_run.html_url }}
      commit: ${{ github.event.workflow_run.head_sha }}
      branch: ${{ github.event.workflow_run.head_branch }}
      tag-name: x-preview
      message: They are development builds, so they may be unstable and have issues. Please report any problems you find.

  experimental:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'experimental' }}
    uses: ./.github/workflows/release_core.yml
    permissions:
      contents: write
      actions: read
    with:
      title: Experimental
      run-id: ${{ github.event.workflow_run.id }}
      run-url: ${{ github.event.workflow_run.html_url }}
      commit: ${{ github.event.workflow_run.head_sha }}
      branch: ${{ github.event.workflow_run.head_branch }}
      tag-name: x-testing
      message: ⚠️ They are experimental development builds, specifically to test upcoming features. **Use at your own risk**.
      label-name: experimental
