name: Nightly Builds

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [trunk]
    types:
      - completed

jobs:
  upload_nightly:
    name: Upload Nightly
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: artifacts
          pattern: "* Release"

      - name: Rename
        shell: bash
        run: |
          mkdir -p release

          function move() {
            [ "$#" == 2 ] || return;
            dir="$(dirname "$1")";
            [ -d "$dir" ] && [ -f "$1" ] && mv "$1" "$2";
          }

          move "artifacts/Windows MSVC Release"/*.zip release/Windows-UZDoom-Nightly.zip
          move "artifacts/MacOS LLVM Release"/*.zip release/MacOS-UZDoom-Nightly.zip
          move "artifacts/Linux LLVM Release"/*.AppImage release/Linux-UZDoom-Nightly.AppImage
          move "artifacts/Linux GCC Release"/*.AppImage release/Linux-Legacy-UZDoom-Nightly.AppImage

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          name: UZDoom Nightly
          tag_name: nightly
          draft: false
          prerelease: true
          make_latest: false
          body: |
            # These are automatically generated development versions based on latest commit to trunk.
            ## WARNING: Nightly builds may be unstable and have issues.
            [Commit:](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.workflow_run.head_sha }})
            ${{ github.event.head_commit.message }}
          generate_release_notes: false
          files: release/**
